spring:
  application:
    name: pharmacy-service
  config:
    import: optional:configserver:http://localhost:8888


management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info   # Mở endpoint /actuator/refresh
  endpoint:
    health:
      show-details: always